pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://jitpack.io' }
        maven{ url 'https://maven.aliyun.com/nexus/content/groups/public/'}
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven{ url 'https://maven.aliyun.com/repository/jcenter'}
        maven { url 'https://maven.aliyun.com/repository/central' }
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://jitpack.io' }
        maven{ url 'https://maven.aliyun.com/nexus/content/groups/public/'}
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven{ url 'https://maven.aliyun.com/repository/jcenter'}
        maven { url 'https://maven.aliyun.com/repository/central' }
        google()
        mavenCentral()
//        flatDir {
//            dirs '../files/config'
//        }
    }
}
rootProject.name = "TheBook"
include ':app'
//include 'libraries:MPChartLib'
